
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
 encrypt:
    key=APODNU3093r2rbjzxcn09u213asdhy08WRFH
